# Generated by Django 3.0.6 on 2020-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toys', '0002_auto_20200507_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='release_data',
            field=models.DateTimeField(),
        ),
    ]
